name: Release Windows

on:
    workflow_dispatch:
        inputs:
            tag:
                description: 'Release tag (e.g., v1.0.0)'
                required: true
                type: string

jobs:
    build-windows:
        permissions:
            contents: write
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v4

            - name: setup Bun
              uses: oven-sh/setup-bun@v1

            - name: Rust cache
              uses: swatinem/rust-cache@v2

            - name: Install Rust stable
              uses: dtolnay/rust-toolchain@stable

            - name: Install frontend dependencies
              run: bun install
              working-directory: ./desktop

            - name: Run pre_build.js
              run: bun scripts/pre_build.js --vulkan

            - name: Import Windows certificate
              if: secrets.WINDOWS_CERTIFICATE != '' && secrets.WINDOWS_CERTIFICATE_PASSWORD != ''
              env:
                WINDOWS_CERTIFICATE: ${{ secrets.WINDOWS_CERTIFICATE }}
                WINDOWS_CERTIFICATE_PASSWORD: ${{ secrets.WINDOWS_CERTIFICATE_PASSWORD }}
              run: |
                # Import certificate
                [IO.File]::WriteAllBytes('cert.pfx', [Convert]::FromBase64String($env:WINDOWS_CERTIFICATE))
                Import-PfxCertificate -Exportable -FilePath "cert.pfx" -CertStoreLocation 'cert:\CurrentUser\My' -Password (ConvertTo-SecureString -String $env:WINDOWS_CERTIFICATE_PASSWORD -Force -AsPlainText)

                # Sign resources
                $signtoolPath = (Get-ChildItem "C:\Program Files (x86)\Windows Kits\10\bin\" -Filter "signtool.exe" -Recurse | Where-Object FullName -like "*\x64\signtool.exe" | Select-Object -First 1).FullName
                &$signtoolPath sign /f cert.pfx /p $env:WINDOWS_CERTIFICATE_PASSWORD /tr http://timestamp.digicert.com /td sha256 /fd sha256 desktop\src-tauri\ffmpeg\bin\x64\*

                # Sign tauri plugin DLLs
                # TODO: remove once https://github.com/tauri-apps/tauri/pull/11676 merged
                C:\msys64\usr\bin\wget.exe https://github.com/tauri-apps/binary-releases/releases/download/nsis-3/nsis-3.zip
                Expand-Archive nsis-3.zip
                Move-Item nsis-3\nsis-3.08 "$env:localappdata\tauri\NSIS"
                Get-ChildItem -Path "$env:LOCALAPPDATA\tauri\NSIS\Plugins" -Filter '*.dll' -Recurse | ForEach-Object { 
                  &$signtoolPath sign /f cert.pfx /p $env:WINDOWS_CERTIFICATE_PASSWORD /tr http://timestamp.digicert.com /td sha256 /fd sha256 $_.FullName
                }

            - name: Build (with certificate)
              if: secrets.WINDOWS_CERTIFICATE != '' && secrets.WINDOWS_CERTIFICATE_PASSWORD != ''
              uses: tauri-apps/tauri-action@v0
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
                  TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
                  TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
                  WINDOWS_CERTIFICATE: ${{ secrets.WINDOWS_CERTIFICATE }}
                  WINDOWS_CERTIFICATE_PASSWORD: ${{ secrets.WINDOWS_CERTIFICATE_PASSWORD }}
              with:
                  tagName: ${{ inputs.tag }}
                  releaseName: "${{ inputs.tag }}"
                  releaseBody: "Windows release for ${{ inputs.tag }} 🪟"
                  prerelease: true
                  args: '--target x86_64-pc-windows-msvc --features "vulkan,server"'
                  projectPath: "./desktop"
                  tauriScript: bunx tauri

            - name: Build (without certificate)
              if: secrets.WINDOWS_CERTIFICATE == '' || secrets.WINDOWS_CERTIFICATE_PASSWORD == ''
              uses: tauri-apps/tauri-action@v0
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
                  WINDOWS_CERTIFICATE: ${{ secrets.WINDOWS_CERTIFICATE }}
                  WINDOWS_CERTIFICATE_PASSWORD: ${{ secrets.WINDOWS_CERTIFICATE_PASSWORD }}
              with:
                  tagName: ${{ inputs.tag }}
                  releaseName: "${{ inputs.tag }}"
                  releaseBody: "Windows release for ${{ inputs.tag }} 🪟"
                  prerelease: true
                  args: '--target x86_64-pc-windows-msvc --features "vulkan,server"'
                  projectPath: "./desktop"
                  tauriScript: bunx tauri